Query and update
zunairkhan811/Vet-clinic pull request #2
Opened 2023-06-06 17:18 UTC by zunairkhan811

- Specie column added

![speciescolumnadded](https://github.com/zunairkhan811/Vet-clinic/assets/116083031/0e987ee1-6185-40de-876f-ac9e2e8c3c58)

- Insert data to animals tabel

![insertnewdata](https://github.com/zunairkhan811/Vet-clinic/assets/116083031/43d94b0c-a33e-4b8a-9d32-cbd4b3d3a27f)

- Add unspecified to column specie

![unspecifiedandrollback;](https://github.com/zunairkhan811/Vet-clinic/assets/116083031/03f5ff7c-02bc-4b8e-93af-ba2aafc46935)

- Different queries and their screenshot

![setspecieendwithmon](https://github.com/zunairkhan811/Vet-clinic/assets/116083031/9adf6c9f-6b3a-46f0-baac-161638f89821)

![setemptyspecietopokemon](https://github.com/zunairkhan811/Vet-clinic/assets/116083031/e603c3b5-902d-47fb-8c70-72fb0997279c)

![createsavepointandweight-1](https://github.com/zunairkhan811/Vet-clinic/assets/116083031/8155c557-57fb-4c34-b0f9-9f550fb147d8)

![rollbacktosp1andupdateweightandcommit](https://github.com/zunairkhan811/Vet-clinic/assets/116083031/147a7ef0-4c3a-4bf8-b183-f0ef8495b690)

![deleteandrollbackwholedata](https://github.com/zunairkhan811/Vet-clinic/assets/116083031/0077d2ea-01b4-4209-97ac-d928b3bf15c3)

![deletegreaterthan1stjan](https://github.com/zunairkhan811/Vet-clinic/assets/116083031/707f1f2e-f964-44de-a896-ea891a08a5b3)

![rollbacktosp1andupdateweightandcommit](https://github.com/zunairkhan811/Vet-clinic/assets/116083031/0c25f051-7887-4ffa-978c-8be165b658ae)

![queryquestions1](https://github.com/zunairkhan811/Vet-clinic/assets/116083031/6c62012a-d97f-4382-b5b1-238fdba7fe1d)

![queryquestion2](https://github.com/zunairkhan811/Vet-clinic/assets/116083031/628f26f7-1f88-4f0b-895a-36c3d075e63d)

2023-06-06 18:02 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @zunairkhan811 👋, 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Use database transactions.
- ✔️Modify and delete data in SQL.
- ✔️Prepare complex queries that answer analytical questions.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 18:02 UTC, abdulhamiid commented on data.sql
> +INSERT INTO ANIMALS VALUES (11,'Ditto','2022-05-14',4,true,22) ;
According to the project requirements, we were instructed to add the following data:
Kindly take note of the negative signs in some of the values 👀
![image](https://github.com/zunairkhan811/Vet-clinic/assets/78251927/de28d10c-5987-43bf-af32-3a2261d662e3)

- It was later in the transaction that all the values were update to positive 💪🛠

![image](https://github.com/zunairkhan811/Vet-clinic/assets/78251927/e6331600-85bb-4609-a7af-c3e1621d9269)

2023-06-06 18:15 UTC, zunairkhan811 commented on data.sql
> +INSERT INTO ANIMALS VALUES (11,'Ditto','2022-05-14',4,true,22) ;
Thanks for the suggestions. Your suggestions have been implemented. 😃

2023-06-06 18:27 UTC, Munsa1 approved these changes
Hi @zunairkhan811, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Made Requested Changes :heavy_check_mark: 
descriptive Pr :heavy_check_mark: 
Good Communication :heavy_check_mark: 

## Optional suggestions
### Important :red_circle: 
- [x] It would have been nice if you could update your screenshots to reflect the changes made

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 00:42 UTC, zunairkhan811 commented
Hi! @Munsa1, Thanks for your suggestion. The screenshot has been updated. 😉

2023-06-07 00:43 UTC, merged